version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: turnos-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=turnos
      - MYSQL_USER=sofi
      - MYSQL_PASSWORD=sofi
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: